# Generated by Django 3.1.5 on 2021-01-12 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст остзыва')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начала записи')),
                ('time', models.TimeField(verbose_name='Время начала записи')),
                ('commentary', models.TextField(verbose_name='Комментарий')),
                ('slug', models.SlugField(unique=True, verbose_name='ЧПУ')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
