# Generated by Django 3.1.5 on 2021-01-13 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210112_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
