# Generated by Django 3.1.5 on 2021-05-07 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210116_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
